apiVersion: apps/v1
kind: Deployment
metadata:
  name: wd-prediction-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: wd-prediction
  template:
    metadata:
      labels:
        app: wd-prediction
    spec:
      containers:
        - name: wd-prediction
          image: yash5090/wd-prediction:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
