apiVersion: v1
kind: Service
metadata:
  name: wd-prediction-service
spec:
  selector:
    app: wd-prediction
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
